language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=lemire
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
  
  branches:
    only:
     - master
     - /^v.*/
