version: 2
jobs:
  "build-and-deploy":
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout

      - run: /opt/python/cp27-cp27mu/bin/python setup.py bdist_wheel
      - run: /opt/python/cp27-cp27m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp34-cp34m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp34-cp34m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel

      - run:
          name: Running auditwheel...
          command: |
              for whl in dist/*.whl; do
                  auditwheel repair "$whl"
              done

      - run:
           name: Uploading to pypi
           command: |
               /opt/python/cp37-cp37m/bin/pip install twine
               /opt/python/cp37-cp37m/bin/twine upload dist/*

workflows:
  version: 2
  tagged-build:
    jobs:
      - "build-and-deploy":
          filters:
            tags:
              only: /^v.*/
