version: 2
jobs:
  build:
    docker: 
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout 
      - run: pip install setuptools
      - run: python setup.py install
      - run: python setup.py bdist_wheel
      - run: twine upload dist/*
