version: 2
jobs:
  build:
    docker: 
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout 
      - run: /opt/python/cp37-cp37mu setup.py bdist_wheel
      - run: twine upload dist/*
